name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  test:
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run tests
        run: cargo test --all
      - name: Check format
        run: cargo fmt --all -- --check

  build-linux-musl:
    needs: test
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install flatc
        run: |
          wget 'https://github.com/google/flatbuffers/releases/download/v24.3.25/Linux.flatc.binary.clang++-15.zip' -O /tmp/flatc.zip
          unzip /tmp/flatc.zip
          sudo mv flatc /usr/bin/flatc
      - name: Install dependencies
        run: |
          sudo apt install cmake clang libssl-dev libsasl2-dev
      - name: Build the binary
        run: cargo build --release --target=x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v4
        with:
          name: cheri_linux_musl
          path: target/x86_64-unknown-linux-musl/release/cheri

  create-release:
    needs: [build-linux-musl]
    timeout-minutes: 20
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: assets/

      - name: Display structure of downloaded files
        run: ls -lR
        working-directory: assets/

      - name: Upload Release Assets
        id: upload_release_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./assets/cheri_linux_musl/cheri
          asset_name: cheri_linux_musl
          asset_content_type: application/octet-stream
